# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:47
from __future__ import unicode_literals

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('douban_id', models.IntegerField(default=1, unique=True, verbose_name='book id in douban')),
                ('status', models.IntegerField(choices=[(0, 'book in the market'), (1, 'someone wish this book, but not bought now'), (2, 'book in the py library'), (3, 'book bas been borrowed by someone')], default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=models.SET(book.models.get_sentinel_user), related_name='PyBook', to='pyuser.PyUser')),
                ('wishers', models.ManyToManyField(blank=True, related_name='bookWishers', to='pyuser.PyUser')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
